#!/bin/bash

# Instituto Stellas - Domain Configuration Script
# Generated by Claude Code Assistant

echo "🌐 INSTITUTO STELLAS - CONFIGURAÇÃO DE DOMÍNIO"
echo "================================================"
echo ""

# Verificar se é root
if [ "$EUID" -ne 0 ]; then
    echo "❌ Este script precisa ser executado como root (sudo)"
    exit 1
fi

# Solicitar domínio
echo "📋 Exemplos de domínio:"
echo "   • stellas.com.br"
echo "   • institutstellas.com.br"
echo "   • institutostellas.org.br"
echo ""
read -p "🌐 Digite seu domínio: " DOMAIN_NAME

if [ -z "$DOMAIN_NAME" ]; then
    echo "❌ Domínio não pode estar vazio"
    exit 1
fi

echo ""
echo "✅ Configurando domínio: $DOMAIN_NAME"
echo ""

# Substituir domínio no arquivo nginx
sed "s/SUBSTITUA_PELO_SEU_DOMINIO/$DOMAIN_NAME/g" /var/www/stellas/landingpage/nginx-stellas.conf > /etc/nginx/sites-available/stellas

# Ativar site
ln -sf /etc/nginx/sites-available/stellas /etc/nginx/sites-enabled/stellas

# Remover site default se existir
if [ -f "/etc/nginx/sites-enabled/default" ]; then
    rm /etc/nginx/sites-enabled/default
    echo "🗑️ Site default removido"
fi

# Testar configuração nginx
echo "🧪 Testando configuração Nginx..."
if nginx -t; then
    echo "✅ Configuração Nginx válida"
    
    # Recarregar nginx
    echo "🔄 Recarregando Nginx..."
    systemctl reload nginx
    echo "✅ Nginx recarregado"
else
    echo "❌ Erro na configuração Nginx"
    exit 1
fi

# Verificar se Next.js está rodando
echo "🔍 Verificando Next.js..."
if curl -s -I http://localhost:5002 | grep -q "200\|301\|302"; then
    echo "✅ Next.js respondendo na porta 5002"
else
    echo "⚠️ Next.js pode não estar respondendo na porta 5002"
    echo "   Verifique se o processo está rodando"
fi

echo ""
echo "🎉 CONFIGURAÇÃO CONCLUÍDA!"
echo ""
echo "🔗 ACESSOS:"
echo "   🌐 HTTP:  http://$DOMAIN_NAME (redirecionará para HTTPS)"
echo "   🔒 HTTPS: https://$DOMAIN_NAME"
echo "   📱 Local: http://localhost:5002"
echo ""
echo "📋 PRÓXIMOS PASSOS:"
echo "   1. Configurar DNS do domínio para apontar para: $(curl -s ipinfo.io/ip)"
echo "   2. Ativar Cloudflare para SSL automático"
echo "   3. Atualizar monitors no Uptime Kuma"
echo "   4. Testar formulário de contato"
echo ""
echo "💡 DICA: Configure o Cloudflare como proxy (nuvem laranja)"
echo "   para SSL automático e CDN global"
echo ""

# Salvar configuração para logs
echo "DOMAIN_NAME=$DOMAIN_NAME" > /var/www/stellas/landingpage/.domain-config
echo "CONFIGURED_DATE=$(date)" >> /var/www/stellas/landingpage/.domain-config
echo "IP_ADDRESS=$(curl -s ipinfo.io/ip)" >> /var/www/stellas/landingpage/.domain-config

echo "✅ Configuração salva em: /var/www/stellas/landingpage/.domain-config"